# Numpy Exercises
https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md

1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [8]:
np.version.version, np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


('1.19.4', None)

3. Create a null vector of size 10 (★☆☆)

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
a = np.arange(50)
print('size in bytes: %3.1f' % (a.itemsize*a.size))

size in bytes: 400.0


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [26]:
# %run `python -c "import numpy; numpy.info(numpy.add)"` (???)

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [31]:
np.insert(np.zeros(9), [4], 1)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [32]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [57]:
a = np.arange(10)
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [58]:
# or
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [81]:
a[9::-1]  #a[starting from :: by]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [82]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [88]:
a = np.array([1,2,0,0,4,0])
np.argwhere(a>0).flatten()

array([0, 1, 4])

In [89]:
# or
np.nonzero(a)

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix (★☆☆)

In [90]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [93]:
np.random.random((3,3,3))

array([[[0.9708153 , 0.91641016, 0.65005873],
        [0.45208724, 0.5236412 , 0.96825427],
        [0.61795715, 0.29327324, 0.20383649]],

       [[0.60260863, 0.03099399, 0.48317303],
        [0.78979606, 0.64550283, 0.27807008],
        [0.02452653, 0.79612044, 0.72093576]],

       [[0.7525211 , 0.7144742 , 0.50133755],
        [0.06536718, 0.79300732, 0.39168222],
        [0.71065771, 0.85994319, 0.58652598]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [95]:
a = np.random.random((10,10))
a.max(), a.min()

(0.9999830969148176, 0.0008924099809327624)

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [97]:
np.random.random(30).mean()

0.46708954200675606

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [99]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [101]:
np.pad(a,1, constant_values=1)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [111]:
# or manually
a = np.ones((4,4))
a[1:-1, 1:-1]=0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [114]:
a = np.random.random((3,3))
a

array([[0.32961271, 0.31347375, 0.91096621],
       [0.90843697, 0.65948386, 0.93682928],
       [0.47547657, 0.00183585, 0.84225656]])

In [118]:
np.pad(a, 1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.32961271, 0.31347375, 0.91096621, 0.        ],
       [0.        , 0.90843697, 0.65948386, 0.93682928, 0.        ],
       [0.        , 0.47547657, 0.00183585, 0.84225656, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])