# Introduction
This notebook includes notes from working through the [Visual Guide to NumPy](https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d). Given that PyTorch uses the same/similar syntax, I think this will be helpful for both.

## NumPy Arrays vs. Lists
* Arithmetic is easier with Arrays
* Arrays are more compact, especially with multiple dimensions
* They are faster when operations can be vectorized.
* Slower than lists when appending items to the end.
* usually homogeneous.

# 1D Arrays: Vectors

In [3]:
import numpy as np
import torch
import math
# from a list
a = np.array([1., 2., 3.])
a, a.dtype

(array([1., 2., 3.]), dtype('float64'))

Quick appends are not supported, so it is important to either grow a list and convert to a NumPy array or to preallocate enough space with `np.zeros` or `np.empty`.

In [4]:
b = np.zeros(3, int)
b, b.dtype

(array([0, 0, 0]), dtype('int64'))

In [5]:
c = np.zeros_like(a)
c, c.dtype

(array([0., 0., 0.]), dtype('float64'))

The `_like` postfix says to match the datatype and dimension of the object passed as argument. See, for example:

In [6]:
x = [1., 2., 3., 4.]
y = np.ones_like(x)
y, y.dtype

(array([1., 1., 1., 1.]), dtype('float64'))

In [7]:
y = np.full_like(x, 5)
y

array([5., 5., 5., 5.])

In [8]:
y = np.empty_like(y)
y, y.dtype

(array([5., 5., 5., 5.]), dtype('float64'))

In [9]:
y = np.ones(5, int)
y = np.empty_like(y)
y

array([     93928188996708,                   0, 3611935507835006001,
       7277828036590656821,                  48])

We can do many of the same things using pytorch.

In [10]:
# argument order is different
x = torch.ones(5, dtype=torch.int64)
x, x.dtype

(tensor([1, 1, 1, 1, 1]), torch.int64)

In [11]:
y = torch.zeros_like(x)
y

tensor([0, 0, 0, 0, 0])

### Sequences
Note that `arange` is susceptible to rounding errors while `linspace` is not.

In [12]:
# start, stop, step
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [13]:
# rounding errors
np.arange(0.4,0.8,0.1), np.arange(0.5,0.8,0.1)

(array([0.4, 0.5, 0.6, 0.7]), array([0.5, 0.6, 0.7, 0.8]))

In [14]:
# start, stop, n_out+1
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

Use `.astype()` to change the type.

In [15]:
a = np.arange(0,10,1)
a, a.dtype

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

In [16]:
a.astype('float')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
a = torch.arange(0,10,1)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a.dtype

torch.int64

In [19]:
# changing types in pytorch
a.type(torch.float64).dtype

torch.float64

## Generating Random Arrays

In [20]:
# integer [0,10) with replacement
a = np.random.randint(0,10,9)
a

array([2, 6, 4, 0, 9, 8, 1, 3, 7])

In [21]:
# uniform [0,1)
np.random.rand(10)

array([0.20897461, 0.11354718, 0.46558342, 0.75119698, 0.89896148,
       0.56865266, 0.95885345, 0.23438105, 0.83898047, 0.72588109])

In [22]:
# standard normal
np.random.randn(3)

array([ 0.27808334, -0.41476924, -1.68102899])

In [23]:
# normal(mean, sd)
np.random.normal(3,2,10)

array([0.71459265, 2.54642965, 3.50568149, 1.79777391, 3.45976271,
       2.62976541, 1.6473506 , 1.74947778, 4.49528329, 2.4122895 ])

## Indexing

We can view subsets of vectors without modifying the original vectors using some of the following methods:

In [24]:
a = np.linspace(1,10,10, dtype=int)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a[1], a[0:2]

(2, array([1, 2]))

In [26]:
a[-3:], a[-5:-3]

(array([ 8,  9, 10]), array([6, 7]))

In [27]:
# every second index
a[::2]

array([1, 3, 5, 7, 9])

In [28]:
a[[1,4,8]]

array([2, 5, 9])

We can use these methods to modify elements of the original vectors.

In [29]:
a[2:4] = np.array([19,20])
a[9]=0
a

array([ 1,  2, 19, 20,  5,  6,  7,  8,  9,  0])

Note that, with lists, `b=a[:]` copies the list. This is not the case with arrays. We must explicitly call the `copy()` method to make a copy.

(I don't fully understand this, based on the following)

In [30]:
a = np.array([1,2,3])
b = a
c = a[:]
a = a[2]
a,b,c

(3, array([1, 2, 3]), array([1, 2, 3]))

### Conditional Indexing

In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a[a>4], a[(a>=3) & (a <= 5)]

(array([5, 6, 7, 8, 9]), array([3, 4, 5]))

In [33]:
a[a !=4], a[~(a==4)] # ~ means not

(array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 5, 6, 7, 8, 9]))

In [34]:
np.any(a>4), np.all(a>4)

(True, False)

## Vector Operations
Vector operations use fast c++ code and avoid slow python loops.

In [35]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

Scalars are *broadcasted* to arrays:

In [36]:
np.array([1,4,6,8,2,3]) + 10

array([11, 14, 16, 18, 12, 13])

Most of python's math functions have numpy equivalents:

In [37]:
a = np.arange(1,5)
a, a**2, np.sqrt(a), np.exp(a), np.log(a)

(array([1, 2, 3, 4]),
 array([ 1,  4,  9, 16]),
 array([1.        , 1.41421356, 1.73205081, 2.        ]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]),
 array([0.        , 0.69314718, 1.09861229, 1.38629436]))

In [38]:
# Dot products
a = np.array([3,4])
b=np.array([10,20])
np.dot(a,b), a@b, np.cross(a,b)

(110, 110, array(20))

## Rounding Arrays

In [39]:
x = np.linspace(2,12,7)
x

array([ 2.        ,  3.66666667,  5.33333333,  7.        ,  8.66666667,
       10.33333333, 12.        ])

In [40]:
np.floor(x), np.ceil(x), np.round(x)

(array([ 2.,  3.,  5.,  7.,  8., 10., 12.]),
 array([ 2.,  4.,  6.,  7.,  9., 11., 12.]),
 array([ 2.,  4.,  5.,  7.,  9., 10., 12.]))

## Basic Stats

In [41]:
x.max(), np.max(x), x.argmax(), x[6], x.var(), x.mean(), x.std()

(12.0, 12.0, 6, 12.0, 11.11111111111111, 7.0, 3.3333333333333335)

## Basic Sorting

In [42]:
y = np.array([3,5,2,8,2,4,6,0])
np.sort(y), y

(array([0, 2, 2, 3, 4, 5, 6, 8]), array([3, 5, 2, 8, 2, 4, 6, 0]))

In [43]:
# in-place sorting
y.sort()
y

array([0, 2, 2, 3, 4, 5, 6, 8])

## Searching
Numpy does not have good, fast methods for finding the first specified element in a vector. According to this tutorial, none of the available methods are "elegant or fast."

In [44]:
a = np.random.randint(0, 100, 100000)
a = np.append(a, 101)
a[-1]

101

In [45]:
%%time
# One (slow) method (works fine for my purposes now)
np.where(a==101)[0][0]

CPU times: user 440 µs, sys: 133 µs, total: 573 µs
Wall time: 319 µs


100000

In [46]:
%%time
# faster for sorted (but sorting takes time)
a.sort()
a[-10:]

CPU times: user 3.55 ms, sys: 63 µs, total: 3.61 ms
Wall time: 3.41 ms


array([ 99,  99,  99,  99,  99,  99,  99,  99,  99, 101])

In [47]:
%%time
np.searchsorted(a,101)

CPU times: user 32 µs, sys: 10 µs, total: 42 µs
Wall time: 35.8 µs


100000

That was very fast, but the sort time was not. The tutorial notes that, overall, this isn't a big deal. We can implement a fast search in C. But float comparisons are hard and don't work out of the box. The `np.allclose` function compares arrays of floats with a given tolerance but isn't perfect.

In [48]:
0.1 + 0.2 == 0.3, 0.1+0.2

(False, 0.30000000000000004)

In [49]:
np.allclose(0.1+0.2, 0.3), math.isclose(0.1+0.2, 0.3)

(True, True)

In [50]:
1e-9==2e-9, np.allclose(1e-9,2e-9), math.isclose(1e-9,2e-9)

(False, True, False)

In [51]:
0.1+0.2-0.3==0, np.allclose(0.1+0.2-0.3,0), math.isclose(0.1+0.2-0.3,0)

(False, True, False)

So there is no silver bullet. All of these approaches fail somewhere. `np.allclose` assumes a typical "scale" of 1. You can adjust the `atol` parameter to address this:

In [52]:
np.allclose(1e-9, 2e-9, atol = 1e-17)

False

Conversely, `math.isclose` makes no scale assumptions and relies on the user to give a reasonable `abs_tol` number.

In [53]:
math.isclose(0.1+0.2-0.3,0, abs_tol=1e-8)

True

# Matrices (2D arrays)

In [54]:
# initialization
a = np.array([[1,2,3],[4,5,6]])
a, a.shape, a.dtype, len(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 dtype('int64'),
 2)

Note: `len(a)` returns `a.shape[0]`. For the funtions such as `zeros` and `empty` to generate matrices, we pass a tuple with the desired dimensions.

Random matrix generation is also similar. Some functions require a list with dimensions e.g. `[3,2]`.

In [55]:
np.zeros((2,3)), np.empty((3,2)), np.eye(3)

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[4.64066916e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [56]:
np.random.randint(0,10,[2,3]), np.random.rand(3,2), np.random.randn(3,2), np.random.normal(10,2,[2,3])

(array([[8, 4, 1],
        [1, 5, 6]]),
 array([[0.26509709, 0.59211602],
        [0.59418476, 0.95792562],
        [0.45886418, 0.06548669]]),
 array([[-1.46486164,  1.66791346],
        [ 1.32472301, -0.07486101],
        [-0.11333231, -1.33446375]]),
 array([[ 8.79910498, 11.61461762, 13.76621804],
        [11.35502759, 14.80675302, 10.62223541]]))

## Indexing of 2D arrays

In [57]:
a = np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
a[1,2], a[1:], a[:2]

(7,
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [59]:
a[:, 1:3], a[-2:, -2:]

(array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[ 7,  8],
        [11, 12]]))

In [97]:
a[::2, 1::2]

array([[ 2,  4],
       [10, 12]])

Recall: no copying is being done. These are only "views" and the original is not modified.

### The axis argument
The `axis` argument is used to tell `numpy` if we are conducting an operation across cells, columns, or other axis/axes.

In [60]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a.sum(), a.sum(axis=0)

(21, array([5, 7, 9]))

In [64]:
a.sum(axis=1)

array([ 6, 15])

## Matrix Arithmetic
- `@` calculates a matrix product

In [70]:
a = a[:,0:2]
b = np.eye(2)
a,b

(array([[1, 2],
        [4, 5]]),
 array([[1., 0.],
        [0., 1.]]))

In [71]:
a+b, a*b, a@b

(array([[2., 2.],
        [4., 6.]]),
 array([[1., 0.],
        [0., 5.]]),
 array([[1., 2.],
        [4., 5.]]))

### Broadcasting
We can multiply matrices by vectors or scalars to different effects using broadcasting.

#### Matrix times Scalar
Multiplying a matrix by a scalar multiplies each element of that matrix by that scalar: 

In [74]:
a = np.arange(1,10).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
a * 9

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

#### Matrix times a (1 by m) Vector

The vector must have the same number of elements as the matrix has columns (or rows; see below). Each column of the matrix is multiplied by the corresponding element of the vector.

In [76]:
a * np.array([1,2,3])

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [87]:
# however, if the dimensions are wrong:
a * np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

#### Matrix times an (m by 1) Vector
Multiplying a matrix by a column vector multiplies each *row* of the matrix by the corresponding element of the vector.

In [85]:
b = np.array([1,2,3]).reshape((3,1))
b

array([[1],
       [2],
       [3]])

In [86]:
a*b

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [89]:
# Compute the outer product
np.array([1,2,3])*np.array([1,2,3]).reshape(3,1)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

Note that in the last example it is a symmetric per-element multiplication. It works the same when the shapes are reversed. To calculate the outer product using an asymmetric linear algebra matrix multiplication the order of the operands should be reversed:

In [95]:
np.array([1,2,3])@np.array([1,2,3])

14

## Row and Column Vectors
By default, 1D arrays are treated as row vectors in 2D operations. There are a few ways to get column vectors *but `transpose` is not one of them*. `T` does work on matrices but not on vectors.

In [101]:
b = np.array([1,2,3])
b.shape, b.T.shape

((3,), (3,))

We can get column vectors using reshape in a few different ways.

In [117]:
b.reshape(1,-1), b.shape # -1 says to automatically calculate the other axis

(array([[1, 2, 3]]), (3,))

In [132]:
# similarly
b = np.array([1,2,3])
b.reshape(3,-1)

array([[1],
       [2],
       [3]])

In [133]:
# or
b = np.array([1,2,3])
b.reshape(3,1)

array([[1],
       [2],
       [3]])

In [134]:
# or
b = np.array([1,2,3])
b.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [135]:
# or
b = np.array([1,2,3])
b[:,None]

array([[1],
       [2],
       [3]])

`None` in the above is a shortcut to `np.newaxis` which adds an empty axis in the designated place.

We've made some column vectors, but not row vectors. the `(3,)` vectors are just 1-D arrays. To make explicit 2D row vectors:

In [128]:
np.array([[1,2,3]]).shape

(1, 3)

In [131]:
b=np.array([1,2,3])[None,:]
b, b.shape

(array([[1, 2, 3]]), (1, 3))

In [141]:
b = np.array([1,2,3])
b.reshape(1,-1).shape

(1, 3)

By the rules of broadcasting, 1D arrays are implicitly interpreted as 2D row vectors, so it is generally not necessary to convert between 1D arrays and 2D row vectors.

## Matrix Manipulations
We can `stack` and `split` arrays.
### Stacking

In [142]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(1,9).reshape(2,4)
a,b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [144]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [145]:
np.hstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [147]:
# need to make sure dimensions are correct
c = np.arange(1,7).reshape(3,2)
c, np.hstack((a,c))

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 1,  2,  3,  4,  1,  2],
        [ 5,  6,  7,  8,  3,  4],
        [ 9, 10, 11, 12,  5,  6]]))

We can run into difficulties when stacking matrices with vectors (works as expected for matrix/matrix and vector/vector). `vstack` will continue to work as anticipated but not `hstack`

In [149]:
b, c = b[1,:], c[:,1]
b,c

(array([5, 6, 7, 8]), array([2, 4, 6]))

In [150]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [151]:
np.hstack((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Why? Because, as noted above, 1D vectors default to row vectors. We can get around this by converting to a row vector or using `column_stack`

In [154]:
x = np.column_stack((a,c))
x

array([[ 1,  2,  3,  4,  2],
       [ 5,  6,  7,  8,  4],
       [ 9, 10, 11, 12,  6]])

In [155]:
# there's also a row_stack
y = np.row_stack((a,b))
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

### Splitting
is the opposite of stacking

In [159]:
np.hsplit(x,[4])

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[2],
        [4],
        [6]])]

In [160]:
np.vsplit(y,[3])

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[5, 6, 7, 8]])]

### Matrix Replication
Use `tile` and `repeat`. Tile takes a matrix and a dimension, and treats that matrix as a single element of a new matrix of the dimensions passed.

In [164]:
a = np.arange(1,5).reshape((2,2))
a, np.tile(a,(2,3))

(array([[1, 2],
        [3, 4]]),
 array([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]]))

`repeat` takes the number of repetitions and the axis along which to repeat. It acts like collated printing. It repeats each element of the original matrix the specified number of times.

In [165]:
a.repeat(3,axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [168]:
a.repeat(3,axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [171]:
# Might make sense to show with scalars
np.repeat(3,6)

array([3, 3, 3, 3, 3, 3])

In [176]:
# it behaves sort of like R's rep()
np.repeat(np.array([2,3]), [3,2])

array([2, 2, 2, 3, 3])

### Deleting and inserting rows and columns

In [179]:
x, np.delete(x,[1,3], axis=1)

(array([[ 1,  2,  3,  4,  2],
        [ 5,  6,  7,  8,  4],
        [ 9, 10, 11, 12,  6]]),
 array([[ 1,  3,  2],
        [ 5,  7,  4],
        [ 9, 11,  6]]))

In [182]:
x, np.delete(x,[2], axis=0)

(array([[ 1,  2,  3,  4,  2],
        [ 5,  6,  7,  8,  4],
        [ 9, 10, 11, 12,  6]]),
 array([[1, 2, 3, 4, 2],
        [5, 6, 7, 8, 4]]))

In [183]:
x, np.insert(x,[2],0,axis=0)

(array([[ 1,  2,  3,  4,  2],
        [ 5,  6,  7,  8,  4],
        [ 9, 10, 11, 12,  6]]),
 array([[ 1,  2,  3,  4,  2],
        [ 5,  6,  7,  8,  4],
        [ 0,  0,  0,  0,  0],
        [ 9, 10, 11, 12,  6]]))

## Sorting

In [184]:
a = np.array([7,4,6,5])
a

array([7, 4, 6, 5])

In [187]:
a.argsort(), a[a.argsort()]

(array([1, 3, 2, 0]), array([4, 5, 6, 7]))

In [189]:
a = np.array([3,2,1,2,4,7,5,6]).reshape(4,-1)
a

array([[3, 2],
       [1, 2],
       [4, 7],
       [5, 6]])

In [192]:
a = a[a[:,0].argsort()]
a

array([[1, 2],
       [3, 2],
       [4, 7],
       [5, 6]])

In [201]:
# use type=stable to sort by multiple columns. I'm not sure what this means.
a = np.column_stack((np.array([3,2,1,2]),np.array([4,7,5,6])))
a

array([[3, 4],
       [2, 7],
       [1, 5],
       [2, 6]])

In [202]:
a = a[a[:,0].argsort(kind='stable')]
a

array([[1, 5],
       [2, 7],
       [2, 6],
       [3, 4]])

In [203]:
a = a[a[:,1].argsort(kind='stable')]
a

array([[3, 4],
       [1, 5],
       [2, 6],
       [2, 7]])

# 3D arrays and above
Array numbering goes from "highest" dimension to lowest. A 3D array is represented as stacked planes: a (4,3,2) array is an array of 4 stacked 3x2 arrays.

In [204]:
np.arange(0,24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

But this isn't completely universal, e.g. with images it's usually (y,x,z) with two pixel coordinates followed by a color coordinate.

Instead of stacking, it may be easier to use the `concatenate` function, especially with higher-dimension data.

In [207]:
a, b = np.arange(0,24).reshape(2,3,4), np.arange(0,12).reshape(2,3,2)

In [211]:
np.concatenate((a,b), axis=2)

array([[[ 0,  1,  2,  3,  0,  1],
        [ 4,  5,  6,  7,  2,  3],
        [ 8,  9, 10, 11,  4,  5]],

       [[12, 13, 14, 15,  6,  7],
        [16, 17, 18, 19,  8,  9],
        [20, 21, 22, 23, 10, 11]]])

In [215]:
a, np.swapaxes(a,axis1 = 1,axis2= 2)

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],
 
        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]]))